<?php /**
 * @author Author "Elsayed Ellabad"  
 * @author Author Email "ellabafci@yahoo.com"
 * @copyright Copyright (c) 2015 Programming by "http://www.mohamedelsayed.net"
 */
// module_load_include('inc', 'content', 'includes/password');
function ellabad_init(){
	//ellabad_save_order();
	// ellabad_make_cart_ordered(1, 1);
	//ellabad_save_order('eee');
	// ellabad_get_cart_item_quantity(218, 1, 0);
	// ellabad_clear_cookie_items();
	//(pr($_COOKIE));
	//die(pr(json_decode($_COOKIE['cart_products'])));
}
function ellabad_menu() {
	$items['admin/custom/orders'] = array(
		'title' => 'All Orders',
		'page callback' => 'ellabad_list_orders_with_pager_content',
		'page arguments' => array(),
        'type' => MENU_CALLBACK,
		'access arguments' => array('access content'),
		//'weight' => -14,
	);
	$items['admin/custom/order/%'] = array(
		'title' => 'View Order',
		'page callback' => 'ellabad_view_order',
		'page arguments' => array(3),
        'type' => MENU_CALLBACK,
		'access arguments' => array('access content'),
		//'weight' => -14,
	);
    return $items;
}

function ellabad_form_alter(&$form, &$form_state, $form_id){
}
/**
 * @param 
 * @return 
 * This is a test function
 */ 
function ellabad_test() {
}
/*
* function to create orders table
*/
function ellabad_update_7100() {
    $schema = array(
        'fields' => array(
            'id' => array(
                'type' => 'serial',
                'unsigned' => TRUE,
                'not null' => TRUE,
            ),
            'uid' => array(
                'type' => 'int',
                'unsigned' => TRUE,
                'not null' => TRUE,
                'default' => '0',
            ),
            'status' => array(
                'type' => 'int',
                'unsigned' => TRUE,
                'not null' => TRUE,
                'default' => '0',
            ),            
            'phone' => array(
        		'type' => 'varchar',
		        'length' => 255,
		        'not null' => FALSE,
		        'default' => ''
            ),
            'address1' => array(
        		'type' => 'varchar',
		        'length' => 255,
		        'not null' => FALSE,
		        'default' => ''
            ),
            'address2' => array(
        		'type' => 'varchar',
		        'length' => 255,
		        'not null' => FALSE,
		        'default' => ''
            ),
            'country' => array(
        		'type' => 'varchar',
		        'length' => 255,
		        'not null' => FALSE,
		        'default' => ''
            ),
            'city' => array(
        		'type' => 'varchar',
		        'length' => 255,
		        'not null' => FALSE,
		        'default' => ''
            ),
            'zip' => array(
        		'type' => 'varchar',
		        'length' => 255,
		        'not null' => FALSE,
		        'default' => ''
            ),
            'created' => array(
                'type' => 'int',
                'unsigned' => TRUE,
                'not null' => TRUE,
                'default' => '0',
            ),
            'updated' => array(
                'type' => 'int',
                'unsigned' => TRUE,
                'not null' => TRUE,
                'default' => '0',
            ),
            'paypal_transaction_id' => array(
        		'type' => 'varchar',
		        'length' => 255,
		        'not null' => FALSE,
		        'default' => ''
            ),
        ),
        'primary key' => array('id'),
    );
    db_create_table('orders', $schema);
}
/**
 * @param 
 * @return 
 * This is a test function
 */ 
function ellabad_save_order($paypal_transaction_id) {
	if(user_is_logged_in()) {
		global $user;
		$uid = $user->uid;
		$status = 0;
		$phone = '';
		$address1 = '';
		$address2 = '';
		$country = '';
		$city =  '';
		$zip = '';
		$created = time();
		$updated = time();
		//$paypal_transaction_id = '';

		if(isset($_COOKIE['cart_phone'])) {
			$phone = $_COOKIE['cart_phone'];
		}
		if(isset($_COOKIE['cart_address1'])) {
			$address1 = $_COOKIE['cart_address1'];
		}
		if(isset($_COOKIE['cart_address2'])) {
			$address2 = $_COOKIE['cart_address2'];
		}
		if(isset($_COOKIE['cart_country'])) {
			$country = $_COOKIE['cart_country'];
		}
		if(isset($_COOKIE['cart_city'])) {
			$city = $_COOKIE['cart_city'];
		}
		if(isset($_COOKIE['cart_zip'])) {
			$zip = $_COOKIE['cart_zip'];
		}
		//function to call when we need
	    $cart_summary = elsayed_get_cart_summary();
	    $cart_price = $cart_summary['price'];
		
		if(isset($_COOKIE['cart_amount'])) {
			$paid_cart_ammount = $_COOKIE['cart_amount'];
		}
		$order_info = array(
			'uid' => $uid,
            'status' => $status,
            'phone' => $phone,
            'address1' => $address1,
            'address2' => $address2,
            'country' => $country,
            'city' => $city,
            'zip' => $zip,
            'created' => $created,
            'updated' => $updated,
            'paypal_transaction_id' => $paypal_transaction_id
	    );
		//if amount not changed
		if($cart_price == $paid_cart_ammount) {
			//Make new order with information received and update cart items
			ellabad_make_order($order_info);
		} else {
			//Get all cart items and compare with ordered items and update quantity if it is changed
			$all_cart_items = array();
	    	$all_cart_items = elsayed_get_cart_query($uid);
	    	//get all cookie items
	    	$ordered_items = json_decode($_COOKIE['cart_products']);
	    	foreach ($all_cart_items as $key => $item) {
	    		$item_quntity = $item->quantity;
	    		$item_nid = $item->nid;
                if(isset($ordered_items->$item_nid)){
		    		$item_quntity_ordered =  $ordered_items->$item_nid;
		    		if($item->quantity != $item_quntity_ordered) {
		    			ellabad_update_cart_changed_item_quantity($item->nid, $item_quntity_ordered, $item->uid );
		    		}
		    	}else{
		    	    $num_deleted = db_delete('orders_products')
                      ->condition('uid', $item->uid)
                      ->condition('order_id', 0)
                      ->condition('nid', $item->nid)
                      ->execute();		    	    
		    	}
	    	}
			//Make new order with information received and update cart items
			ellabad_make_order($order_info);	    	 
		}
	}
}
/*
* Function to update all cart items to be ordered if make order success
*/
function ellabad_make_cart_ordered($uid = 0, $order_id = 0) {
    if($uid == 0){
        global $user;
        $uid = $user->uid;
    }
    if($uid != 0 and $order_id != 0){
       
    	db_update('orders_products')
                ->fields(array(
                    'order_id' => $order_id,
                ))
                ->condition('uid', $uid, '=')
                ->condition('order_id', 0, '=')
                ->execute();
    }
}
/*
* Function to update quantity ofproduct  of cart if it changed during payment cycle
*/
function ellabad_update_cart_changed_item_quantity($nid = 0, $quantity = 0  ,$uid = 0) {
    if($nid != 0 && $uid != 0){       
		db_update('orders_products')
            ->fields(array(
                'quantity' => $quantity,
            ))
            ->condition('nid', $nid, '=')
            ->condition('uid', $uid, '=')            
            ->condition('order_id', 0, '=') 
            ->execute();	
    }
}
/*
* function to update cart item quantity if it is updated during payment
*/
function ellabad_get_cart_item_quantity($item_id, $uid, $order_id = 0) {
	$item_quntity = db_query('SELECT quantity FROM {orders_products} WHERE (nid = :nid) AND (uid = :uid) AND (uid = :uid) AND (order_id = :order_id) ', 
        array(':nid' => $item_id,':uid' => $uid, 'order_id' => $order_id))->fetchField();
	return $item_quntity;
}
/*
* function to clear cookie items
*/
function ellabad_clear_cookie_items() {
	unset($_COOKIE['cart_products']);
	unset($_COOKIE['cart_phone']);
	unset($_COOKIE['cart_address1']);
	unset($_COOKIE['cart_address2']);
	unset($_COOKIE['cart_zip']);
	unset($_COOKIE['cart_city']);
	unset($_COOKIE['cart_amount']);
	unset($_COOKIE['cart_currency_code']);
	unset($_COOKIE['cart_business']);
	
}

/*
* Function to make order
*/
function ellabad_make_order($order_info) {
	$order_id = db_insert('orders')
        ->fields(array(
            'uid' => $order_info['uid'],
            'status' => $order_info['status'],
            'phone' => $order_info['phone'],
            'address1' => $order_info['address1'],
            'address2' => $order_info['address2'],
            'country' => $order_info['country'],
            'city' => $order_info['city'],
            'zip' => $order_info['zip'],
            'created' => $order_info['created'],
            'updated' => $order_info['updated'],
            'paypal_transaction_id' => $order_info['paypal_transaction_id']
        ))->execute();
    
    ellabad_make_cart_ordered($order_info['uid'], $order_id);
	ellabad_clear_cookie_items();
    
}
/*
* Function to list all orders with page contnent
*/
function ellabad_list_orders_with_pager_content() {
	$header = array(
		//array('data' => t('Weight'), 'field' => 'weight', 'sort' => 'asc'),
		//array('data' => t('id'), 'field' => 'domain_id', 'sort' => 'desc'),
		array('data' => t('Order ID')),
		array('data' => t('Status')),
		array('data' => t('Operations')),
	);
	global $base_url;
	$status = arg(3);
	$status_val = '';
	if($status == 'active'){
		$status_val = 1;
	} else if($status == 'pending') {
		$status_val = 0;
	}

	$uid = arg(4);
	$query = db_select('orders', 'o');
	//$query->join('users', 'u', 'o.uid= u.uid');
	$query->fields('o', array('id', 'status' ));
	if($status == 'active' || $status =='pending' ){
		$query->condition('o.status', $status_val, '=');
	}
	if($uid != ''){
		$query->condition('o.uid', $uid, '=');
	}
	$table_sort = $query->extend('TableSort') // Add table sort extender.
		->orderByHeader($header); // Add order by headers.
		$pager = $table_sort->extend('PagerDefault')
		->limit(20);
	$result = $pager->execute();
	$rows = array();
	$output = '<ul class="action-links">
		<li><a href="'.$base_url.'/admin/custom/orders/all">All</a></li>
		<li><a href="'.$base_url.'/admin/custom/orders/active">Active</a></li>
		<li><a href="'.$base_url.'/admin/custom/orders/pending">Pending</a></li>
		</ul>';
	foreach($result as $res){
		$rows[] = array($res->id, ellabad_get_order_status($res->status), "<a href='$base_url/admin/custom/order/$res->id'>View</a>");		
	}
	// If rows are not empty theme and display the rows.
	if (!empty($rows)){
		$output .= theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('id' => 'sort-table')));
		$output .= theme('pager');
	}else{
		$output .= t("No results found.");
	}

	return $output;
}
/*
* Function to return order status text
*/
function ellabad_get_order_status($order_status) {
	$status = '';
	if($order_status != ''){
		if($order_status == 0){
			$status = 'Pending';
		} elseif($order_status == 1){
			$status = 'Active';
		} else {
			$status = 'Cancelled';
		}
	}
	return $status;
}

/*
* Function to view order page informtion
*/
function ellabad_view_order() {
	return 'Welcome to order no'.arg(3);
}
